#ifndef DRIVE_HARDWARE_DEFINITIONS_H
#define DRIVE_HARDWARE_DEFINITIONS_H

#include "driver/gpio.h"

// Motor drivers

// Left motor

#define L_IN_A_PIN  CONFIG_TANK_DRIVE_LEFT_MOTOR_IN_A_PIN
#define L_IN_B_PIN  CONFIG_TANK_DRIVE_LEFT_MOTOR_IN_B_PIN
#define L_MODE_PIN  CONFIG_TANK_DRIVE_LEFT_MOTOR_MODE_PIN
#define L_SLEEP_PIN CONFIG_TANK_DRIVE_LEFT_MOTOR_SLEEP_PIN

// Right motor

#define R_IN_A_PIN  CONFIG_TANK_DRIVE_RIGHT_MOTOR_IN_A_PIN
#define R_IN_B_PIN  CONFIG_TANK_DRIVE_RIGHT_MOTOR_IN_B_PIN
#define R_MODE_PIN  CONFIG_TANK_DRIVE_RIGHT_MOTOR_MODE_PIN
#define R_SLEEP_PIN CONFIG_TANK_DRIVE_RIGHT_MOTOR_SLEEP_PIN

#endif  // DRIVE_HARDWARE_DEFINITIONS_H
